language: r
r:
  - 3.1
##  - release
  - devel

sudo: false

cache: packages

os:
  - linux
##  - osx

install:
  - Rscript -e 'pkg <- c("roxygen2", "RcppEigen", "numDeriv", "parallel"); if(!all(pkg%in%installed.packages())) install.packages(pkg)'

script:
  - make cran-version
  - make cran-check
  - make install
  - echo "library(TMB);precompile();runExample(all=TRUE)" | R --slave
  - make test

notifications:
  email:
    on_success: never
    on_failure: never

